export const P2P_COMMAND_ID_BASE = 1000;

export enum EID {
  HANDSHAKE = P2P_COMMAND_ID_BASE + 1,
  TIMED_SYNC = P2P_COMMAND_ID_BASE + 2,
  PING = P2P_COMMAND_ID_BASE + 3,
  REQUEST_STATE_INFO = P2P_COMMAND_ID_BASE + 4,
  REQUEST_NETWORK_STATE = P2P_COMMAND_ID_BASE + 5,
  REQUEST_PEER_ID = P2P_COMMAND_ID_BASE + 6,
}
