export enum Command {
  BASE = 2000,
  NOTIFY_NEW_BLOCK,
  NOTIFY_NEW_TRANSACTIONS,
  NOTIFY_REQUEST_GET_OBJECTS,
  NOTIFY_RESPONSE_GET_OBJECTS,
  NOTIFY_PLACE_HOLDER,
  NOTIFY_REQUEST_CHAIN,
  NOTIFY_RESPONSE_CHAIN_ENTRY,
  NOTIFY_REQUEST_TX_POOL,
}
